use mattools_db;

--SELECT 'MID','MERCHANT_DBA_NAME','STATUS_EDC','CITY','ID_NUMBER','MSO','SOURCE_CODE','POS_1','WILAYAH','CHANNEL','TYPE_MID','OPEN_DATE','TAHUN','BULAN','generate_at','update_at' 
SELECT
'ORG'	,
'MID'	,
'MERCHANT_DBA_NAME'	,
'STATUS_EDC'	,
'OPENDATE'	,
'CITY'	,
'STATE'	,
'DATE_LAST_MAINTAIN'	,
'CONTACT_PERSON'	,
'TELP1'	,
'TELP2'	,
'MSO'	,
'MMO'	,
'DDA'	,
'MERCHANT_TYPE'	,
'CHAIN_STORE'	,
'SOURCE_CODE'	,
'MERCHANT_NAME'	,
'ALAMAT1'	,
'ALAMAT2'	,
'KOTA1'	,
'KOTA2'	,
'ZIPCODE'	,
'kolom24'	,
'MCC1'	,
'MCC2'	,
'kolom27'	,
'kolom28'	,
'kolom29'	,
'POS1'	,
'POS2'	,
'POS3'	,
'PLAN1'	,
'PLAN2'	,
'PLAN3'	,
'DATE_LAST_STATEMENT'	,
'kolom37'	,
'kolom38'	,
'kolom39'	,
'kolom40'	,
'kolom41'	,
'kolom42'	,
'kolom43'	,
'kolom44'	,
'kolom45'	,
'kolom46'	,
'kolom47'	,
'NPWP'	,
'ACCOUNT_NO'	,
'BANK_NAME'	,
'kolom51'	,
'kolom52'	,
'kolom53'	,
'kolom54'	,
'kolom55'	,
'kolom56'	,
'kolom57'	,
'kolom58'	,
'MDR_VISA_BNI'	,
'kolom60'	,
'kolom61'	,
'kolom62'	,
'kolom63'	,
'kolom64'	,
'kolom65'	,
'MDR_VISA_OTHER'	,
'kolom67'	,
'kolom68'	,
'kolom69'	,
'kolom70'	,
'kolom71'	,
'kolom72'	,
'MDR_MC_BNI'	,
'kolom74'	,
'kolom75'	,
'kolom76'	,
'kolom77'	,
'kolom78'	,
'kolom79'	,
'MDR_MC_DEBIT_BNI'	,
'kolom81'	,
'kolom82'	,
'kolom83'	,
'kolom84'	,
'kolom85'	,
'kolom86'	,
'MDR_MC_OTHERS'	,
'kolom88'	,
'kolom89'	,
'kolom90'	,
'kolom91'	,
'kolom92'	,
'kolom93'	,
'MDR_JCB_BNI'	,
'kolom95'	,
'kolom96'	,
'kolom97'	,
'kolom98'	,
'kolom99'	,
'kolom100'	,
'MDR_JCB_OTHERS'	,
'CLOSED_REASON'	,
'ACCOUNT_NO_2'	,
'kolom104'	



UNION ALL 

SELECT 
ORG	,
 MID	,
 MERCHANT_DBA_NAME	,
 STATUS_EDC	,
 OPENDATE	,
 CITY	,
 STATE	,
 DATE_LAST_MAINTAIN	,
 CONTACT_PERSON	,
 TELP1	,
 TELP2	,
 MSO	,
 MMO	,
 DDA	,
 MERCHANT_TYPE	,
 CHAIN_STORE	,
 SOURCE_CODE	,
 MERCHANT_NAME	,
 ALAMAT1	,
 ALAMAT2	,
 KOTA1	,
 KOTA2	,
 ZIPCODE	,
 kolom24	,
 MCC1	,
 MCC2	,
 kolom27	,
 kolom28	,
 kolom29	,
 POS1	,
 POS2	,
 POS3	,
 PLAN1	,
 PLAN2	,
 PLAN3	,
 DATE_LAST_STATEMENT	,
 kolom37	,
 kolom38	,
 kolom39	,
 kolom40	,
 kolom41	,
 kolom42	,
 kolom43	,
 kolom44	,
 kolom45	,
 kolom46	,
 kolom47	,
 NPWP	,
 ACCOUNT_NO	,
 BANK_NAME	,
 kolom51	,
 kolom52	,
 kolom53	,
 kolom54	,
 kolom55	,
 kolom56	,
 kolom57	,
 kolom58	,
 MDR_VISA_BNI	,
 kolom60	,
 kolom61	,
 kolom62	,
 kolom63	,
 kolom64	,
 kolom65	,
 MDR_VISA_OTHER	,
 kolom67	,
 kolom68	,
 kolom69	,
 kolom70	,
 kolom71	,
 kolom72	,
 MDR_MC_BNI	,
 kolom74	,
 kolom75	,
 kolom76	,
 kolom77	,
 kolom78	,
 kolom79	,
 MDR_MC_DEBIT_BNI	,
 kolom81	,
 kolom82	,
 kolom83	,
 kolom84	,
 kolom85	,
 kolom86	,
 MDR_MC_OTHERS	,
 kolom88	,
 kolom89	,
 kolom90	,
 kolom91	,
 kolom92	,
 kolom93	,
 MDR_JCB_BNI	,
 kolom95	,
 kolom96	,
 kolom97	,
 kolom98	,
 kolom99	,
 kolom100	,
 MDR_JCB_OTHERS	,
 CLOSED_REASON	,
 ACCOUNT_NO_2	,
 kolom104	


INTO OUTFILE 'C:/xampp/htdocs/mattools/MISMER/BSK_TXT/EDC_MISMER0624.csv' 
FIELDS TERMINATED BY '|' FROM mismer_all a
WHERE 
-- LEFT(a.MID,1) IN (2,3,5,8,9) OR LEFT(a.SOURCE_CODE,1)='U'
LEFT(a.MID,1) =2 AND LEFT(a.SOURCE_CODE,1)!='U' 
-- AND a.MSO!='912' AND LEFT(a.MSO,1)!='Q'
 AND EXTRACT(YEAR FROM STR_TO_DATE(concat(concat(20,SUBSTRING(a.OPENDATE,5,2)),'/',SUBSTRING(a.OPENDATE,3,2),'/',SUBSTRING(a.OPENDATE,1,2)), '%Y/%m/%d') )=2019
; 

--mysql -u root mattools_db < C:/xampp/htdocs/mattools/bat/MISMER/GENERATE_MISMER/EXPORT_CSV_ALL.sql


-- RUN IN CMD
--mysql -u root mattools_db -e "SELECT 'MID','MERCHANT_DBA_NAME','STATUS_EDC','CITY','ID_NUMBER','MSO','SOURCE_CODE','POS_1','WILAYAH','CHANNEL','TYPE_MID','OPEN_DATE','TAHUN','BULAN','generate_at','update_at' UNION ALL SELECT MID,MERCHANT_DBA_NAME,STATUS_EDC,CITY,ID_NUMBER,MSO,SOURCE_CODE,POS_1,WILAYAH,CHANNEL,TYPE_MID,OPEN_DATE,TAHUN,BULAN,generate_at,update_at INTO OUTFILE 'C:/xampp/htdocs/mattools/MISMER/BSK_TXT/EXPORT_EDC_DETAIL_123.csv' FIELDS TERMINATED BY ',' FROM edc_detail"
